prometheus.prometheusSpec.externalLabels.cluster: deve-teste-sobre-values
prometheusOperator.admissionWebhooks.patch.annotations:
  argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/hook-delete-policy: HookSucceeded
grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.pombo.meuovo
  persistence:
    enabled: true
    size: 4Gi
  adminPassword: pipoca
