apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cluster: xixi-dev-us-east5-001
    umbrella: "false"
    wave: "2"
  name: keda
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: sre
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.15.1
    chart: keda
    helm:
      values: |
        metricsServer:
          replicaCount: 1
        operator:
          replicaCount: 1
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: generic
        webhooks:
          replicaCount: 1
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: 
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

