apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "3"
  labels:
    cluster: xixi-dev-us-east5-001
    umbrella: "false"
    wave: "3"
  name: kubed
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: sre
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/metadata/annotations
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
  source:
    path: ''
    repoURL: https://charts.getup.io/getupcloud
    targetRevision: v0.13.2
    chart: kubed
    helm:
      values: |-
        config:
          clusterName: xixi
          configSourceNamespace: core
        operator:
          tag: v0.13.2
        replicaCount: 1
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: generic
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

