apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cluster: xixi-dev-us-east5-001
    umbrella: "false"
    wave: "2"
  name: oauth2-proxy
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: sre
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.3.0
    chart: oauth2-proxy
    helm:
      values: |-
        config:
          annotations: {}
          clientID: "34550581416"
          clientSecret: "GOCSPX"
          cookieSecret: "cm9zY2E="
        configFile: |-
          email_domains = [ "arromaba.com" ]
          upstreams = [ "file:///dev/null" ]
        ingress:
          className: nginx
          enabled: true
          hosts:
          - pombo.bola.azmarela.com
          path: /oauth2
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: generic
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
