apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cluster: poarara
    umbrella: "false"
    wave: "2"
  name: rabbitmq-cluster-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: sre
    server: https://kubernetes.default.svc
  source:
    path: config/installation
    repoURL: https://github.com/rabbitmq/cluster-operator.git
    targetRevision: v2.5.0
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2

