apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    xargocd.argoproj.io/instance: apps
    umbrella: "true"
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - Validate=true
  sources:
    - path: apps
      repoURL: https://github.com/adonaicosta/argo-apps.git
      targetRevision: HEAD
    - path: apps/apps-infra
      repoURL: https://github.com/adonaicosta/argo-apps.git
      targetRevision: HEAD
#    directory:
#      recurse: true
