apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    umbrella: "false"
    wave: "2"
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      values: |
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: bola@quadrada
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: generic
        installCRDs: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
